import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Jost from "next/font/google";    
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { frFR } from "@clerk/localizations";
import { Navbar } from "./components/Navbar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});
const parkisans = localFont({
  src: "./fonts/Parkinsans-Medium.ttf",
  variable: "--font-paarkisans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={frFR}>
      <html lang="en">
        <body className={`${inter.className}  overflow-hidden`}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
